### PR TITLE
Front end

### PR DESCRIPTION
**Pull request by incogitance**
Circle CI kickin my butt

### CODE REVIEW

**Comment by incogitance** [comment]
WOOOOHOOO circleCI working now

**Review by WarrenMfg — APPROVED** [review]
Sweet! Loving the " error: 'something blew up' "...

**Review by thelensguy — APPROVED** [review]
is there a reason why it is yarn test instead of npm test?

**Comment by incogitance** [comment]
Default values... Mine has been updated to npm

**Comment by incogitance** [comment]
Default config for circle ci uses yarn. I have changed it to npm but have not pushed that version yet

**Pull request merged**
